---
title: Exploratory Data Analysis
author: Eduardo Blancas Reyes (eb3079), Valmik Patel (vp2382), Aaron Sadholz (as5401), Jose A Alvarado-Guzman (jaa2220)
date: April 24, 2018
output: html_document
---

# 1. Introduction

Music has evolved immensely throughout the years. This is evident in no place more than it is in song lyrics. Lyrics have evolved over time across genres and geographies reflecting the current affairs of that time and the evolution of culture. We wanted to explore these relationships between lyrics, time, geography, and genre. Thus we decided to have song lyrics exploration as the topic for our project.


We explored and tried to answer different questions in the project. Primarily, we looked at how lyrics varied across time, band and geography. We looked at the sentiment scores and their variation across these factors. In addition, we explored the topics covered by the songs as well by using topic modeling on the song lyrics. The similarity of bands was also determined based on their choice of lyrics.

All our code is publicly available on [Github](https://github.com/edublancas/song-lyrics).

The interactive component of this project, which displays information on individual artists is available [here](http://bl.ocks.org/valmikkpatel/raw/450a721204f0f3788133c045f700278f)

## 1.1 Team members

* Aaron Sadholz (as5401)
    - Coded python topic modeling scrips
    - Wrote report section 4.5. Topic Modeling.
    - Wrote report section 6. Conclusion

* Eduardo Blancas Reyes (eb3079)
    - Coded Python cleaning/processing scripts used in `bootstrap` (except for topic modeling and sentiment analysis)
    - Wrote report section 4.1 Data cleaning
    - Wrote report section 4.4. Distance-based comparisons

* Jose A Alvarado-Guzman (jaa2220)
    - Coded R sentiment scripts
    - Wrote report section 3.1 Missing Data
    - Wrote report section 4.3 Sentiment analysis

* Valmik Patel (vp2382)
    - Made the interactive component
    - Wrote report section 1 Introduction
    - Wrote report section 2 Description of data

