
# 2. Description of Data

We used the million songs database along with the Musixmatch database for this project. These datasets were created by The Laboratory for the Recognition and Organization of Speech and Audio (LabROSA) at Columbia University. The million songs dataset contains data points like song name, artist name, year, song length and tempo for a million songs released between 1922-2011 chosen by LabROSA. The Musixmatch dataset contains data about lyrics of around 515,000 of these songs. The other songs are not covered due to copyright limitations. For this dataset, the words in the lyrics were stemmed and we are given the occurrences of top 5000 stemmed words in all songs. This was again done to deal with copyright issues.

The data was collected using csv files provided by LabROSA. The csv files were preprocessed and cleaned and converted to feather files for efficient reading into R. The majority of the songs in the dataset come from the period of 20 years from 1990 to 2010. We have lyrics data from 515576 songs by 72665 artists. Artist based in the US account for the majority of the songs and more than 40,000 artists have less than 5 songs in the dataset. Although this is not an all encompassing list of songs, it still is a huge dataset that can tell us about some compelling trends in song lyrics.

