#!/usr/bin/env bash
mkdir data
wget -O data/mxm_dataset_train.txt.zip http://labrosa.ee.columbia.edu/millionsong/sites/default/files/AdditionalFiles/mxm_dataset_train.txt.zip
wget -O data/mxm_dataset_test.txt.zip http://labrosa.ee.columbia.edu/millionsong/sites/default/files/AdditionalFiles/mxm_dataset_test.txt.zip

unzip data/mxm_dataset_train.txt.zip -d data/
unzip data/mxm_dataset_test.txt.zip -d data/