#!/usr/bin/env Rscript

source('lib/functions.R')
reqs <- c('tidyverse', 'rjson', 'dplyr', 'ggplot2', 'feather','scales'
          'reshape2', 'wordcloud', 'knitr', 'maps', 'extracat',
          'slam', 'GGally', 'viridis','plyr','data.table','tidytext', 'stringr')

installNeededPackages(reqs)
