#!/usr/bin/env python

"""
Parses a <SEP> separated txt file and outputs an Apache Feather binary file
"""
import argparse
import logging
import pandas as pd


def main():
    # instantiate a logger to print useful information about the progress
    logger = logging.getLogger(__name__)

    # config logger to INFO level
    logging.basicConfig(level=logging.INFO)

    # use docstring at the top as description for the script
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument('path_to_data', type=str,
                        help='Path to the <SEP> separated txt data')
    parser.add_argument('path_to_output', type=str,
                        help='Output path for the feather file')
    parser.add_argument('columns', type=str,
                        help='comma separated column names')

    args = parser.parse_args()
    path_to_data = args.path_to_data
    path_to_output = (args.path_to_output
                      if args.path_to_output.endswith('.feather')
                      else args.path_to_output + '.feather')

    df = pd.read_csv(path_to_data, sep='<SEP>',
                     names=args.columns.split(','),
                     engine='python')
    df = df.reset_index()
    df.drop('index', axis=1, inplace=True)

    logger.info('Saving file in {}'.format(path_to_output))
    df.to_feather(path_to_output)


if __name__ == "__main__":
    main()
