```{r}
library(feather)
library(dplyr)
library(ggplot2)
```

```{r}
song_cols <- c('artist_name', 'title')
```

```{r}
tracks <- read_feather('data/transform/unique_tracks.feather')
lyrics <- read_feather('data/transform/mxm_dataset_100.feather')
```

```{r}
# not all tracks have lyrics so do a left join
df <- left_join(lyrics, tracks, by='track_id')
dim(df)
```

```{r}
# normalize counts to have proportion instead...
words_per_song <- apply(df[, 2:101], 1, sum)

# if there are songs without words (it may be because we only got the top k
# words), divide by one to avoid NAs
words_per_song[words_per_song == 0] <- 1

df[, 2:101] <- df[, 2:101] / words_per_song
```

```{r}
# which are the largest counts?
max_counts <- apply(df[, 2:101], 2, max)
max_counts

which_max <- apply(df[, 2:101], 2, which.max)

print(df[which_max, song_cols], n=40)
```

```{r}
df_ <- filter(df, love > 0)

# take a look at the distribution of some words
ggplot(df_, aes(me)) + geom_histogram(bins=30)
```

```{r}
# let's check the particular use of a word in some artists
a <- filter(df, artist_name=='Oasis')
b <- filter(df, artist_name=='Maroon 5')

mean(a$love)
mean(b$love)
```

```{r}
t(df[which.max(df$love), ])

# weird counts...
t(df[which.max(df$me), ])

# Maroon 5, Oasis, The Kooks, Arctic Monkeys
one_artist <-filter(df, artist_name == 'Maroon 5')
one_artist$title
cor(one_artist$she, one_artist$love)

cor_ <- function(df, a, b){
    artist_name <- df$artist_name[1]

    # at least 20 songs and at least 3 points to plot
    if (nrow(df) > 20 & sum(df[[a]] & df[[b]]) > 3){
        return(data.frame(artist_name=artist_name,
               val=cor(df[[a]], df[[b]])))
    }else{
        return(data.frame(artist_name=artist_name,
                          val=0))
    }
}

colnames(df)

s <- sample_n(df, 40000)
a <- s$love > 0
b <- s$she > 0
idx <- a & b
plot(s$love[idx], s$she[idx])
cor(s$love[idx], s$she[idx])


df_ <- filter(df, artist_name %in% c('Maroon 5', 'Oasis'))

test <- df %>% group_by(artist_name) %>% do(cor_(., 'you', 'love'))

filter(test, val > .4)

arrange(test, desc(val))[1:20, ]
arrange(test, desc(val))[20:30, ]
arrange(test, desc(val))[30:40, ]
arrange(test, desc(val))[40:50, ]
arrange(test, desc(val))[50:60, ]
arrange(test, val)

m <- filter(df, artist_name == 'Metallica')
nrow(m)
plot(m$you, m$love)
cor(m$you, m$love)


dist_matrix <- as.matrix(dist(one_artist[, 2:51]))

apply(dist_matrix, 1, which.max)

t(one_artist[21,])
t(one_artist[37,])

t(one_artist[which.max(one_artist$love), ])
t(one_artist[which.max(one_artist$she), ])
t(one_artist[which.max(one_artist$die), ])
```