
```{r}
library(feather)
library(dplyr)
```


```{r}
tracks <- read_feather('data/transform/unique_tracks.feather')
lyrics <- read_feather('data/transform/mxm_embeddings.feather')
```


```{r}
head(lyrics)
dim(lyrics)
```

```{r}
df <- left_join(lyrics, tracks, by='track_id')

colnames(df)

sub <- filter(df, artist_name %in% c('Maroon 5', 'Oasis', 'Phoenix',
             'Coldplay', 'The Killers', 'Daft Punk'))

sub <- sample_frac(df, 0.01)

dim(sub)
```

```{r}
dist_matrix <- as.matrix(dist(sub[, 2:51]))
diag(dist_matrix) <- NA

dim(dist_matrix)

similar <- apply(dist_matrix, 1, which.min)

similar
a <- as.numeric(names(similar))
b <- as.numeric(similar)
idx <- 250
t(sub[a[idx],])
t(sub[b[idx],])
```

```{r}
w <- filter(df, artist_name == 'Deep Purple')
w[44, c('artist_name', 'title')]
```

```{r}
w <- filter(df, artist_name == "Eric Clapton")
print(w[, c('artist_name', 'title')], n=100)

```


```{r}
# may be fun to look for outliers, songs that are apart from the rest...
# we should do entity resolution with names Ramones vs The Ramones
w <- filter(df, artist_name == "The Clash")
print(w[, c('artist_name', 'title')], n=100)

distances <- as.matrix(pdist(w[6, 2:51], df[, 2:51]))

sorted <- sort(distances, index.return=TRUE)

sorted$x[1:50]
idxs <- sorted$ix[1:50]
idxs

matches <- df[idxs, c('artist_name', 'title')]
print(df[idxs, c('artist_name', 'title')], n=30)
```