---
title: "R Notebook"
output: html_notebook
---

# Analyzing word correlation

```{r}
library(feather)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
source('experiments/eduardo/util.R')
```

```{r}
# load data
df <- read_feather('data/transform/bag_of_words_top_1000.feather')
df <- read_feather('data/transform/embeddings.feather')

# get columns corresponding to the metadata words
columns <- colnames(df)
columns_metadata <- columns[endsWith(columns, '_')]
columns_lyrics <- columns[!endsWith(columns, '_')]
```

```{r}
# artists tagged as
artist_ids <- terms[terms$mbtag == 'disco', ]$artist_id

# why this is giving me more than length(artist_ids)???
# maybe there is not a 1-1 correspondence between artist id and name
artist_names <- unique(filter(df, artist_id %in% artist_ids)$artist_name)

```

```{r}

select(df, -ends_with('_'))
a <- df %>% filter(artist_name == 'Oasis')

[, 'you']

b <- filter(df, artist_name == 'Oasis')

[, 'love']
cor(a, b)
```


```{r}
cor_ <- function(df, a, b){
    artist_name <- df$artist_name[1]

    # at least 20 songs and at least 3 points to plot
    if (nrow(df) > 20 & sum(df[[a]] & df[[b]]) > 3){
        return(data.frame(artist_name=artist_name,
               val=cor(df[[a]], df[[b]])))
    }else{
        return(data.frame(artist_name=artist_name,
                          val=0))
    }
}

test <- df %>% group_by(artist_name) %>% do(cor_(., 'you', 'love'))

# FIX NORMALIZATION IN YEAR COLUMN LYRICS DF
cor_year <- df %>% group_by(year.y) %>% do(cor_(., 'you', 'love'))

cor_year[order(cor_year$val)]

cor_year[order(cor_year$val, decreasing=TRUE),] 


selected <- c('Oasis', 'The Verve', 'Maroon 5', 'Sum 41')
filter(test, artist_name %in% selected)
```

# Analyzing topics

Generating topics:

```{r}
distances <- embeddings_distances('data/clean/embeddings_subset.json')

topic <- closest_k(distances, 'sun')
topic

df_topic <- load_topic(topic, df, metadata_cols)
df_topic <- df_topic[order(-df_topic$sun_topic),]
```

```{r}
head(df_topic)

head(filter(df_topic, artist_name == 'Maroon 5'))
```


# Finding similar years

```{r}
mean_words <- function(df, cols){
    data.frame(t(colMeans(df[, cols])))
}

by_year <- df %>% group_by(release_year_) %>% do(mean_words(., columns_lyrics))
by_year <- data.frame(by_year)
by_year <- by_year[!is.na(by_year$release_year_), ]
rownames(by_year) <- by_year$release_year_

distances <- as.matrix(dist(by_year, diag=TRUE, upper=TRUE))
distances <- melt(as.matrix(distances), varnames = c("row", "col"))
distances <- distances[distances$row > distances$col,]
```

```{r}
ggplot(distances, aes(x=row, y=col)) + 
    geom_tile(aes(fill=value), color="white") + 
    coord_fixed()
```

## Finding similar artists

```{r}
# subset artists - using genre is an easy way to group artists
sub <- df %>% filter(genre_ == 'Rock') %>% sample_n(50)
sub$artist_name_
```

```{r}
by_artist <- sub %>% group_by(artist_name_) %>% do(mean_words(., columns_lyrics))
by_artist <- data.frame(by_artist)
by_artist <- by_artist[!is.na(by_artist$artist_name_), ]
rownames(by_artist) <- by_artist$artist_name_

distances <- as.matrix(dist(by_artist, diag=TRUE, upper=TRUE))
distances <- melt(as.matrix(distances), varnames = c("row", "col"))
```

```{r}
ggplot(distances, aes(x=row, y=col)) + 
    geom_tile(aes(fill=value), color="white") + 
    coord_fixed() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Finding similar genres


```{r}
genre <- table(df$genre_)
top_genres <- names(genre_[genre_ > 80])

hist(table(df$genre_))
```

```{r}
by_genre <- df %>%filter(genre_ %in% top_genres) %>%
                group_by(genre_) %>%
                do(mean_words(., columns_lyrics))

by_genre <- data.frame(by_genre)
by_genre <- by_genre[!is.na(by_genre$genre_), ]
rownames(by_genre) <- by_genre$genre_

distances <- as.matrix(dist(by_genre))
distances <- melt(as.matrix(distances), varnames = c("row", "col"))
```

```{r}
ggplot(distances, aes(x=row, y=col)) + 
    geom_tile(aes(fill=value), color="white") + 
    coord_fixed() +
    theme(axis.text.x = element_text(angle=45, hjust=1))
```


## Find similar songs (bag of words and embeddings)

TODO: visualize artists in two dimensions using PCA

## Songs that talk about the same topic