#!/usr/bin/env python

"""
Parse musixmatch dataset in json format and output a Apache Feather file
where each row is a song in dense format throught word embeddings
"""
import logging
import json

from song_lyrics.parse import load_json_data, json_glove
from song_lyrics.transform import bows2embeddings, bow2embedding


def main():
    logging.basicConfig(level=logging.INFO)

    logger = logging.getLogger(__name__)

    # load word embeddings subset
    glove = json_glove('data/clean/embeddings_subset.json')

    logger.info('Loaded {:,} embeddings...'.format(len(glove)))

    # load musixmatch data
    path_to_data = 'data/clean/mxm_dataset.json'
    words, track_ids, bows = load_json_data(path_to_data)

    # maybe for embeddings makes more sense to use top words within each song
    # than overall, also add the possibility to select words. Or maybe do not
    # select max words at all
    MAX_WORDS = 100

    # convert bag of words to dense representation using embeddings
    bows2embeddings(bows[:100], words, track_ids[:100], glove)


    bow2embedding(bows[0], words, glove)


if __name__ == "__main__":
    main()
