#!/usr/bin/env bash
mkdir data
wget -O data/raw/mxm_dataset_train.txt.zip \
    http://labrosa.ee.columbia.edu/millionsong/sites/default/files/AdditionalFiles/mxm_dataset_train.txt.zip
wget -O data/raw/mxm_dataset_test.txt.zip \
    http://labrosa.ee.columbia.edu/millionsong/sites/default/files/AdditionalFiles/mxm_dataset_test.txt.zip

unzip data/raw/mxm_dataset_train.txt.zip -d data/raw
unzip data/raw/mxm_dataset_test.txt.zip -d data/raw